Style updates
Aiwizo/react-file-dropzone pull request #1
Opened 2021-02-10 17:22 UTC by fippli

- Possibility to customize component styles
- Aiwizo applications styles are installed out of the box

2021-02-10 17:44 UTC, Bartbob641 approved these changes

2021-02-10 17:57 UTC, Bartbob641 requested changes
doesn't pass checks 😮

2021-02-10 19:11 UTC, Jim-Holmstroem approved these changes

2021-02-10 21:23 UTC, Jim-Holmstroem approved these changes

2021-02-11 07:49 UTC, Bartbob641 approved these changes

2021-02-11 08:53 UTC, merged